require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - log/**/*
    - tmp/**/*
    - bin/**/*
    - node_modules/**/*
    - db/schema.rb
    - vendor/**/*

Capybara/FeatureMethods:
  EnabledMethods:
    - feature
    - scenario

RSpec/MultipleExpectations:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Metrics/BlockLength:
  Exclude:
    - lib/capistrano/tasks/**/*.rake
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*